# Generated by Django 6.0.2 on 2026-03-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_timezone'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='occasiontype',
            new_name='events_occa_club_id_8d9228_idx',
            old_name='events_occa_club_id_5fd6d0_idx',
        ),
        migrations.RenameIndex(
            model_name='venuereservation',
            new_name='events_venu_club_id_09f943_idx',
            old_name='events_venu_club_id_2b50b1_idx',
        ),
        migrations.RenameIndex(
            model_name='venuereservation',
            new_name='events_venu_club_id_3d6fe4_idx',
            old_name='events_venu_club_id_4a8d01_idx',
        ),
        migrations.RenameIndex(
            model_name='venuereservation',
            new_name='events_venu_club_id_1b9110_idx',
            old_name='events_venu_club_id_6df9d5_idx',
        ),
        migrations.RenameIndex(
            model_name='venuereservation',
            new_name='events_venu_club_id_8cb314_idx',
            old_name='events_venu_club_id_d8752d_idx',
        ),
        migrations.RenameIndex(
            model_name='venuereservation',
            new_name='events_venu_club_id_515ccc_idx',
            old_name='events_venu_club_id_446974_idx',
        ),
        migrations.RenameIndex(
            model_name='venuereservation',
            new_name='events_venu_club_id_48ad56_idx',
            old_name='events_venu_club_id_a58fa5_idx',
        ),
        migrations.AlterField(
            model_name='occasiontype',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='venuereservation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='clubs.club'),
        ),
    ]
