# Generated by Django 6.0.2 on 2026-03-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('sale_created', 'Sale Created'), ('sale_refunded', 'Sale Refunded'), ('price_override', 'Price Override'), ('stock_adjustment', 'Stock Adjustment'), ('stock_restock', 'Stock Restock'), ('stock_refund', 'Stock Refund'), ('low_stock_alert_created', 'Low Stock Alert Created'), ('occasion_type_created', 'Occasion Type Created'), ('occasion_type_updated', 'Occasion Type Updated'), ('occasion_type_deactivated', 'Occasion Type Deactivated'), ('reservation_created', 'Reservation Created'), ('reservation_payment_recorded', 'Reservation Payment Recorded'), ('reservation_cancelled', 'Reservation Cancelled'), ('reservation_refunded', 'Reservation Refunded'), ('gate_ticket_type_created', 'Gate Ticket Type Created'), ('gate_ticket_type_updated', 'Gate Ticket Type Updated'), ('gate_ticket_type_deactivated', 'Gate Ticket Type Deactivated'), ('gate_entry_day_created', 'Gate Entry Day Created'), ('gate_entry_day_updated', 'Gate Entry Day Updated'), ('gate_ticket_sale_created', 'Gate Ticket Sale Created'), ('gate_ticket_checked_in', 'Gate Ticket Checked In'), ('gate_ticket_voided', 'Gate Ticket Voided')], max_length=50),
        ),
    ]
