# Generated by Django 6.0.2 on 2026-03-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_dailyclubreport_csv_file'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyclubreport',
            new_name='reporting_d_club_id_98c1e5_idx',
            old_name='reporting_d_club_id_d77857_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyclubreport',
            new_name='reporting_d_report__205591_idx',
            old_name='reporting_d_report__0f9786_idx',
        ),
    ]
