# Generated by Django 6.0.2 on 2026-03-19 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_timezone'),
        ('inventory', '0003_stockmovement_inventory_s_club_id_922724_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('threshold_value', models.PositiveIntegerField()),
                ('stock_quantity_at_trigger', models.PositiveIntegerField()),
                ('recipient_user_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='clubs.club')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='inventory.product')),
                ('triggered_by_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_low_stock_alerts', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['club', 'is_active'], name='inventory_l_club_id_3ca5dd_idx'), models.Index(fields=['club', 'product'], name='inventory_l_club_id_77684a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('threshold_value__gte', 0)), name='low_stock_threshold_value_non_negative'), models.CheckConstraint(condition=models.Q(('stock_quantity_at_trigger__gte', 0)), name='low_stock_quantity_at_trigger_non_negative')],
            },
        ),
    ]
