# Generated by Django 6.0.2 on 2026-03-22 16:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_timezone'),
        ('inventory', '0004_lowstockalert'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='cost_price_positive',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='selling_price_positive',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gt', 0)), name='cost_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gt', 0)), name='selling_price_positive'),
        ),
    ]
