# Generated by Django 6.0.2 on 2026-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_cost_price_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sold_30d',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
