# Generated by Django 6.0.2 on 2026-02-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['slug'], name='clubs_club_slug_9373ca_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['subscription_end'], name='clubs_club_subscri_dca04e_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['is_active'], name='clubs_club_is_acti_ef120d_idx'),
        ),
    ]
