# Generated by Django 6.0.2 on 2026-04-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_timezone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='club',
            name='clubs_club_subscri_dca04e_idx',
        ),
        migrations.RemoveField(
            model_name='club',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='club',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='club',
            name='subscription_start',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
