# Generated by Django 6.0.2 on 2026-03-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_timezone'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gateentryday',
            new_name='tickets_gat_club_id_40479a_idx',
            old_name='tickets_gat_club_id_887665_idx',
        ),
        migrations.RenameIndex(
            model_name='gateentryday',
            new_name='tickets_gat_club_id_3ea4cb_idx',
            old_name='tickets_gat_club_id_0defd1_idx',
        ),
        migrations.RenameIndex(
            model_name='gateticket',
            new_name='tickets_gat_club_id_3b06db_idx',
            old_name='tickets_gat_club_id_744733_idx',
        ),
        migrations.RenameIndex(
            model_name='gateticket',
            new_name='tickets_gat_club_id_9a66aa_idx',
            old_name='tickets_gat_club_id_560f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='gateticket',
            new_name='tickets_gat_club_id_844263_idx',
            old_name='tickets_gat_club_id_c237e5_idx',
        ),
        migrations.RenameIndex(
            model_name='gateticket',
            new_name='tickets_gat_code_6d2bd9_idx',
            old_name='tickets_gat_code_03cb0b_idx',
        ),
        migrations.RenameIndex(
            model_name='gateticketsale',
            new_name='tickets_gat_club_id_223cd3_idx',
            old_name='tickets_gat_club_id_59c5de_idx',
        ),
        migrations.RenameIndex(
            model_name='gateticketsale',
            new_name='tickets_gat_club_id_dbb94f_idx',
            old_name='tickets_gat_club_id_0f727a_idx',
        ),
        migrations.RenameIndex(
            model_name='gateticketsale',
            new_name='tickets_gat_club_id_ebd800_idx',
            old_name='tickets_gat_club_id_3442eb_idx',
        ),
        migrations.RenameIndex(
            model_name='gateticketsale',
            new_name='tickets_gat_club_id_b195c5_idx',
            old_name='tickets_gat_club_id_4216a5_idx',
        ),
        migrations.RenameIndex(
            model_name='gatetickettype',
            new_name='tickets_gat_club_id_751ccf_idx',
            old_name='tickets_gat_club_id_52e638_idx',
        ),
        migrations.RenameIndex(
            model_name='gatetickettype',
            new_name='tickets_gat_club_id_63e74d_idx',
            old_name='tickets_gat_club_id_716dcc_idx',
        ),
        migrations.AlterField(
            model_name='gateentryday',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='gateticket',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='gateticketsale',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='gatetickettype',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='clubs.club'),
        ),
    ]
