# Generated by Django 6.0.2 on 2026-03-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_refunded_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_club_id_ce0f04_idx',
            old_name='sales_sale_club_id_refunded_idx',
        ),
    ]
